apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-data
  labels:
    app.kubernetes.io/name: chromadb
    app.kubernetes.io/part-of: kumio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
