apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ninko.backend.fullname" . }}-data
  namespace: {{ include "ninko.namespace" . }}
  labels:
    {{- include "ninko.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
  {{- if .Values.backend.persistence.storageClass }}
  storageClassName: {{ .Values.backend.persistence.storageClass }}
  {{- end }}
