apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-settings
  namespace: ninko
data:
  settings.yml: |
    use_default_settings: true
    server:
      port: 8080
      bind_address: "0.0.0.0"
      secret_key: "REPLACE_WITH_RANDOM_SECRET_KEY"
    search:
      formats:
        - html
        - json
