apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data
  labels:
    app.kubernetes.io/name: ninko-backend
    app.kubernetes.io/part-of: ninko
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
