apiVersion: v1
kind: Secret
metadata:
  name: kumio-secrets
  labels:
    app.kubernetes.io/name: kumio-backend
    app.kubernetes.io/part-of: kumio
type: Opaque
stringData:
  SQLITE_SECRETS_KEY: "a39ff360874e4779c60a0cd6646f7a5b5e83a0e384d00306b4873c097fff7841"
